//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Helpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemeRoutine
    {
        public string SPECIFIC_CATALOG { get; set; }
        public string SPECIFIC_SCHEMA { get; set; }
        public string SPECIFIC_NAME { get; set; }
        public string ROUTINE_CATALOG { get; set; }
        public string ROUTINE_SCHEMA { get; set; }
        public string ROUTINE_NAME { get; set; }
        public string ROUTINE_TYPE { get; set; }
        public string MODULE_CATALOG { get; set; }
        public string MODULE_SCHEMA { get; set; }
        public string MODULE_NAME { get; set; }
        public string UDT_CATALOG { get; set; }
        public string UDT_SCHEMA { get; set; }
        public string UDT_NAME { get; set; }
        public string DATA_TYPE { get; set; }
        public Nullable<int> CHARACTER_MAXIMUM_LENGTH { get; set; }
        public Nullable<int> CHARACTER_OCTET_LENGTH { get; set; }
        public string COLLATION_CATALOG { get; set; }
        public string COLLATION_SCHEMA { get; set; }
        public string COLLATION_NAME { get; set; }
        public string CHARACTER_SET_CATALOG { get; set; }
        public string CHARACTER_SET_SCHEMA { get; set; }
        public string CHARACTER_SET_NAME { get; set; }
        public Nullable<byte> NUMERIC_PRECISION { get; set; }
        public Nullable<short> NUMERIC_PRECISION_RADIX { get; set; }
        public Nullable<int> NUMERIC_SCALE { get; set; }
        public Nullable<short> DATETIME_PRECISION { get; set; }
        public string INTERVAL_TYPE { get; set; }
        public Nullable<short> INTERVAL_PRECISION { get; set; }
        public string TYPE_UDT_CATALOG { get; set; }
        public string TYPE_UDT_SCHEMA { get; set; }
        public string TYPE_UDT_NAME { get; set; }
        public string SCOPE_CATALOG { get; set; }
        public string SCOPE_SCHEMA { get; set; }
        public string SCOPE_NAME { get; set; }
        public Nullable<long> MAXIMUM_CARDINALITY { get; set; }
        public string DTD_IDENTIFIER { get; set; }
        public string ROUTINE_BODY { get; set; }
        public string ROUTINE_DEFINITION { get; set; }
        public string EXTERNAL_NAME { get; set; }
        public string EXTERNAL_LANGUAGE { get; set; }
        public string PARAMETER_STYLE { get; set; }
        public string IS_DETERMINISTIC { get; set; }
        public string SQL_DATA_ACCESS { get; set; }
        public string IS_NULL_CALL { get; set; }
        public string SQL_PATH { get; set; }
        public string SCHEMA_LEVEL_ROUTINE { get; set; }
        public Nullable<short> MAX_DYNAMIC_RESULT_SETS { get; set; }
        public string IS_USER_DEFINED_CAST { get; set; }
        public string IS_IMPLICITLY_INVOCABLE { get; set; }
        public System.DateTime CREATED { get; set; }
        public System.DateTime LAST_ALTERED { get; set; }
    }
}
