//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessControl
    {
        public int AccessControlID { get; set; }
        public int UserID { get; set; }
        public int NMVNTaskID { get; set; }
        public int OrganizationalUnitID { get; set; }
        public int AccessLevel { get; set; }
    }
}
