//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    
    public partial class AdditionalGoodsReceiptVoucherText
    {
        public string VoucherText1 { get; set; }
        public string VoucherText2 { get; set; }
        public string VoucherText3 { get; set; }
        public string VoucherText4 { get; set; }
        public string Reference { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string VATInvoiceNo { get; set; }
        public Nullable<System.DateTime> VATInvoiceDate { get; set; }
    }
}
