//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commodity
    {
        public Commodity()
        {
            this.GoodsReceiptDetails = new HashSet<GoodsReceiptDetail>();
            this.PurchaseInvoiceDetails = new HashSet<PurchaseInvoiceDetail>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            this.SalesInvoiceDetails = new HashSet<SalesInvoiceDetail>();
            this.ServiceContracts = new HashSet<ServiceContract>();
            this.StockTransferDetails = new HashSet<StockTransferDetail>();
            this.TransferOrderDetails = new HashSet<TransferOrderDetail>();
            this.QuotationDetails = new HashSet<QuotationDetail>();
        }
    
        public int CommodityID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string OfficialName { get; set; }
        public string OriginalName { get; set; }
        public Nullable<int> PreviousCommodityID { get; set; }
        public int CommodityCategoryID { get; set; }
        public int CommodityTypeID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> PiecePerPack { get; set; }
        public Nullable<int> QuantityAlert { get; set; }
        public decimal ListedPrice { get; set; }
        public decimal GrossPrice { get; set; }
        public string PurchaseUnit { get; set; }
        public string SalesUnit { get; set; }
        public string Packing { get; set; }
        public string Origin { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> LeadTime { get; set; }
        public string HSCode { get; set; }
        public Nullable<bool> Discontinue { get; set; }
        public string Specifycation { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> InActive { get; set; }
    
        public virtual CommodityCategory CommodityCategory { get; set; }
        public virtual CommodityType CommodityType { get; set; }
        public virtual ICollection<GoodsReceiptDetail> GoodsReceiptDetails { get; set; }
        public virtual ICollection<PurchaseInvoiceDetail> PurchaseInvoiceDetails { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual ICollection<SalesInvoiceDetail> SalesInvoiceDetails { get; set; }
        public virtual ICollection<ServiceContract> ServiceContracts { get; set; }
        public virtual ICollection<StockTransferDetail> StockTransferDetails { get; set; }
        public virtual ICollection<TransferOrderDetail> TransferOrderDetails { get; set; }
        public virtual ICollection<QuotationDetail> QuotationDetails { get; set; }
    }
}
