//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCategory
    {
        public CustomerCategory()
        {
            this.CustomerCategories1 = new HashSet<CustomerCategory>();
            this.Customers = new HashSet<Customer>();
        }
    
        public int CustomerCategoryID { get; set; }
        public string Name { get; set; }
        public Nullable<int> AncestorID { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<CustomerCategory> CustomerCategories1 { get; set; }
        public virtual CustomerCategory CustomerCategory1 { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
