//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.PurchaseInvoices = new HashSet<PurchaseInvoice>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.Quotations = new HashSet<Quotation>();
            this.SalesInvoices = new HashSet<SalesInvoice>();
            this.ServiceContracts = new HashSet<ServiceContract>();
        }
    
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public string OfficialName { get; set; }
        public int CustomerCategoryID { get; set; }
        public int CustomerTypeID { get; set; }
        public int TerritoryID { get; set; }
        public string AddressNo { get; set; }
        public string VATCode { get; set; }
        public string Telephone { get; set; }
        public string Facsimile { get; set; }
        public string AttentionName { get; set; }
        public string AttentionTitle { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<double> LimitAmount { get; set; }
        public string Remarks { get; set; }
        public bool InActive { get; set; }
        public bool IsCustomer { get; set; }
        public bool IsSupplier { get; set; }
        public bool IsFemale { get; set; }
    
        public virtual CustomerCategory CustomerCategory { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual EntireTerritory EntireTerritory { get; set; }
        public virtual Territory Territory { get; set; }
        public virtual ICollection<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<Quotation> Quotations { get; set; }
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
        public virtual ICollection<ServiceContract> ServiceContracts { get; set; }
    }
}
