//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    
    public partial class GoodsReceiptGetPurchaseInvoice
    {
        public string Description { get; set; }
        public string Remarks { get; set; }
        public int GoodsReceiptTypeID { get; set; }
        public int VoucherID { get; set; }
        public string CustomerName { get; set; }
        public string AttentionName { get; set; }
        public string Telephone { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Reference { get; set; }
    }
}
