//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    
    public partial class GoodsReceiptViewDetail
    {
        public int GoodsReceiptDetailID { get; set; }
        public int GoodsReceiptID { get; set; }
        public int CommodityID { get; set; }
        public string CommodityName { get; set; }
        public string Origin { get; set; }
        public string Packing { get; set; }
        public Nullable<decimal> QuantityRemains { get; set; }
        public decimal Quantity { get; set; }
        public string ChassisCode { get; set; }
        public string EngineCode { get; set; }
        public string ColorCode { get; set; }
        public string Remarks { get; set; }
        public int WarehouseID { get; set; }
        public int VoucherID { get; set; }
        public int VoucherDetailID { get; set; }
        public string CommodityCode { get; set; }
        public string WarehouseCode { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Amount { get; set; }
        public decimal VATPercent { get; set; }
        public decimal VATAmount { get; set; }
        public decimal GrossAmount { get; set; }
        public int CommodityTypeID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public decimal GrossPrice { get; set; }
    }
}
