//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsReceiptDetail
    {
        public GoodsReceiptDetail()
        {
            this.SalesInvoiceDetails = new HashSet<SalesInvoiceDetail>();
            this.StockTransferDetails = new HashSet<StockTransferDetail>();
        }
    
        public int GoodsReceiptDetailID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int GoodsReceiptID { get; set; }
        public int GoodsReceiptTypeID { get; set; }
        public int VoucherID { get; set; }
        public int VoucherDetailID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public int CommodityID { get; set; }
        public int CommodityTypeID { get; set; }
        public int WarehouseID { get; set; }
        public string Origin { get; set; }
        public string Packing { get; set; }
        public decimal Quantity { get; set; }
        public decimal QuantityIssue { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal VATPercent { get; set; }
        public decimal GrossPrice { get; set; }
        public decimal Amount { get; set; }
        public decimal VATAmount { get; set; }
        public decimal GrossAmount { get; set; }
        public string ChassisCode { get; set; }
        public string EngineCode { get; set; }
        public string ColorCode { get; set; }
        public string Remarks { get; set; }
        public int LocationID { get; set; }
    
        public virtual Commodity Commodity { get; set; }
        public virtual GoodsReceipt GoodsReceipt { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual ICollection<SalesInvoiceDetail> SalesInvoiceDetails { get; set; }
        public virtual ICollection<StockTransferDetail> StockTransferDetails { get; set; }
    }
}
