//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_30_06_33
    {
        public int AutoID { get; set; }
        public int CommodityID { get; set; }
        public string Description { get; set; }
        public string DescriptionOfficial { get; set; }
        public string OriginalName { get; set; }
        public string UnitSales { get; set; }
        public Nullable<int> WHInputID { get; set; }
        public Nullable<System.DateTime> WHInputDate { get; set; }
        public string SerialNo { get; set; }
        public string FixedAsset { get; set; }
        public string ColorCode { get; set; }
        public Nullable<int> WHLocationID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string WarehouseName { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<double> QuantityEnd { get; set; }
        public Nullable<double> UPriceNMDInventory { get; set; }
        public Nullable<int> ItemCategoryID { get; set; }
        public Nullable<int> ItemTypeID { get; set; }
        public string ItemCategoryName1 { get; set; }
        public string ItemCategoryName2 { get; set; }
    }
}
