//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTerm
    {
        public PaymentTerm()
        {
            this.PurchaseInvoices = new HashSet<PurchaseInvoice>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.SalesInvoices = new HashSet<SalesInvoice>();
        }
    
        public int PaymentTermID { get; set; }
        public int TermPaymentCategoryID { get; set; }
        public string Name { get; set; }
        public string Remarks { get; set; }
        public bool IsDefault { get; set; }
        public int CalculateID { get; set; }
    
        public virtual ICollection<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
    }
}
