//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    
    public partial class PendingPartTransferOrder
    {
        public int TransferOrderDetailID { get; set; }
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public int WarehouseID { get; set; }
        public string WarehouseCode { get; set; }
        public Nullable<decimal> QuantityOrderPending { get; set; }
        public decimal QuantityAvailable { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public int CommodityTypeID { get; set; }
        public Nullable<int> SupplierID { get; set; }
    }
}
