//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    
    public partial class PurchaseInvoiceGetSupplier
    {
        public int SupplierID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAttentionName { get; set; }
        public string CustomerTelephone { get; set; }
        public string CustomerAddressNo { get; set; }
        public string CustomerEntireTerritoryEntireName { get; set; }
    }
}
