//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    
    public partial class PurchaseInvoiceGetPurchaseOrder
    {
        public int PurchaseOrderID { get; set; }
        public string PurchaseOrderReference { get; set; }
        public int SupplierID { get; set; }
        public string AttentionName { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public System.DateTime PurchaseOrderEntryDate { get; set; }
        public string PurchaseOrderConfirmReference { get; set; }
        public Nullable<System.DateTime> PurchaseOrderConfirmDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAttentionName { get; set; }
        public string CustomerTelephone { get; set; }
        public string CustomerAddressNo { get; set; }
        public string CustomerEntireTerritoryEntireName { get; set; }
    }
}
