//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoiceDetail
    {
        public int PurchaseInvoiceDetailID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int PurchaseInvoiceID { get; set; }
        public int PurchaseOrderDetailID { get; set; }
        public int PurchaseOrderID { get; set; }
        public int SupplierID { get; set; }
        public int CommodityID { get; set; }
        public int CommodityTypeID { get; set; }
        public string Origin { get; set; }
        public string Packing { get; set; }
        public decimal Quantity { get; set; }
        public decimal QuantityReceipt { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal VATPercent { get; set; }
        public decimal GrossPrice { get; set; }
        public decimal Amount { get; set; }
        public decimal VATAmount { get; set; }
        public decimal GrossAmount { get; set; }
        public string ChassisCode { get; set; }
        public string EngineCode { get; set; }
        public string ColorCode { get; set; }
        public string Remarks { get; set; }
        public int LocationID { get; set; }
    
        public virtual Commodity Commodity { get; set; }
        public virtual PurchaseInvoice PurchaseInvoice { get; set; }
        public virtual PurchaseOrderDetail PurchaseOrderDetail { get; set; }
    }
}
