//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAWDATA_07_2015
    {
        public int AutoID { get; set; }
        public Nullable<double> STT { get; set; }
        public int WarehouseID { get; set; }
        public int CommodityTypeID { get; set; }
        public string DONHANG { get; set; }
        public string LOHANG { get; set; }
        public System.DateTime NGAYGIAO { get; set; }
        public string MAHANG { get; set; }
        public string TEN_VN { get; set; }
        public string TEN_EN { get; set; }
        public string MAUXE { get; set; }
        public string SOKHUNG { get; set; }
        public string SOMAY { get; set; }
        public double SOLUONG { get; set; }
        public double DONGIA { get; set; }
        public Nullable<int> CommodityID { get; set; }
        public Nullable<int> CommodityCategoryID { get; set; }
        public string CommodityCategoryName { get; set; }
    }
}
