//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceContract
    {
        public ServiceContract()
        {
            this.Quotations = new HashSet<Quotation>();
            this.SalesInvoices = new HashSet<SalesInvoice>();
        }
    
        public int ServiceContractID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Reference { get; set; }
        public int CustomerID { get; set; }
        public int ServiceContractTypeID { get; set; }
        public Nullable<int> SalesInvoiceDetailID { get; set; }
        public int CommodityID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string LicensePlate { get; set; }
        public string ChassisCode { get; set; }
        public string EngineCode { get; set; }
        public string ColorCode { get; set; }
        public string AgentName { get; set; }
        public Nullable<int> BeginningMeters { get; set; }
        public Nullable<int> EndingMeters { get; set; }
        public Nullable<System.DateTime> BeginningDate { get; set; }
        public Nullable<System.DateTime> EndingDate { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public int UserID { get; set; }
        public int PreparedPersonID { get; set; }
        public int OrganizationalUnitID { get; set; }
        public int LocationID { get; set; }
        public int ApproverID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime EditedDate { get; set; }
        public bool Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public bool InActive { get; set; }
        public bool InActivePartial { get; set; }
        public Nullable<System.DateTime> InActiveDate { get; set; }
    
        public virtual ICollection<Quotation> Quotations { get; set; }
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
        public virtual ServiceContractType ServiceContractType { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Commodity Commodity { get; set; }
        public virtual SalesInvoiceDetail SalesInvoiceDetail { get; set; }
        public virtual Location Location { get; set; }
    }
}
