//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    
    public partial class ServiceContractGetVehiclesInvoice
    {
        public int SalesInvoiceDetailID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public string ChassisCode { get; set; }
        public string EngineCode { get; set; }
        public string ColorCode { get; set; }
        public Nullable<System.DateTime> CustomerBirthday { get; set; }
        public string CustomerTelephone { get; set; }
        public string CustomerAddressNo { get; set; }
        public string CustomerEntireTerritoryEntireName { get; set; }
        public int LimitedMonthWarranty { get; set; }
        public int LimitedKilometreWarranty { get; set; }
        public System.DateTime BeginningDate { get; set; }
        public Nullable<System.DateTime> EndingDate { get; set; }
    }
}
