//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    
    public partial class ServiceContractResult
    {
        public Nullable<int> ServiceContractID { get; set; }
        public string ServiceContractReference { get; set; }
        public int ServiceContractCommodityID { get; set; }
        public string ServiceContractCommodityCode { get; set; }
        public string ServiceContractCommodityName { get; set; }
        public Nullable<System.DateTime> ServiceContractPurchaseDate { get; set; }
        public string ServiceContractLicensePlate { get; set; }
        public string ServiceContractChassisCode { get; set; }
        public string ServiceContractEngineCode { get; set; }
        public string ServiceContractColorCode { get; set; }
        public string ServiceContractAgentName { get; set; }
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> CustomerBirthday { get; set; }
        public string CustomerTelephone { get; set; }
        public string CustomerAddressNo { get; set; }
        public string CustomerEntireTerritoryEntireName { get; set; }
    }
}
