//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferOrderDetail
    {
        public TransferOrderDetail()
        {
            this.StockTransferDetails = new HashSet<StockTransferDetail>();
        }
    
        public int TransferOrderDetailID { get; set; }
        public int TransferOrderID { get; set; }
        public int CommodityID { get; set; }
        public int WarehouseID { get; set; }
        public decimal Quantity { get; set; }
        public decimal QuantityTransfer { get; set; }
        public string Remarks { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int CommodityTypeID { get; set; }
        public int LocationID { get; set; }
    
        public virtual ICollection<StockTransferDetail> StockTransferDetails { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Commodity Commodity { get; set; }
        public virtual TransferOrder TransferOrder { get; set; }
    }
}
