//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCNB_T07
    {
        public int Id { get; set; }
        public Nullable<double> STT { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string WarehouseCode { get; set; }
        public Nullable<int> SourceLocationID { get; set; }
        public Nullable<System.DateTime> NGAYGIAO { get; set; }
        public Nullable<int> CommodityTypeID { get; set; }
        public Nullable<int> CommodityID { get; set; }
        public string MAHANG { get; set; }
        public string TEN_VN { get; set; }
        public string SOKHUNG { get; set; }
        public string SOMAY { get; set; }
        public string MAUXE { get; set; }
        public Nullable<double> SL { get; set; }
        public Nullable<int> DestinationWarehouseID { get; set; }
        public string KHONHANXE { get; set; }
        public string GHICHU { get; set; }
    }
}
