//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    
    public partial class VehicleTransferViewDetail
    {
        public int StockTransferDetailID { get; set; }
        public int StockTransferID { get; set; }
        public Nullable<int> GoodsReceiptDetailID { get; set; }
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public int WarehouseID { get; set; }
        public string WarehouseCode { get; set; }
        public string ChassisCode { get; set; }
        public string EngineCode { get; set; }
        public Nullable<decimal> QuantityAvailable { get; set; }
        public decimal Quantity { get; set; }
        public string Remarks { get; set; }
        public string ColorCode { get; set; }
        public Nullable<int> TransferOrderDetailID { get; set; }
        public int CommodityTypeID { get; set; }
        public Nullable<int> SupplierID { get; set; }
    }
}
